wooferzfg/tww-rando-bot

randobot/handler.py

In cases where the wrong seed is rolling (Whoops) this would allow a state reset without leaving the race room. This wouldn't work for Spoiler Log seeds, and is locked to Race Monitors.

Implemented an Override

---

randobot/handler.py

Appends the end of the raceroom with the permalink. At some point it should also Prefix it with the style of race. 
Examples would be 
Standard : Permalink
Spoiler : Permalink
Fun : Permalink
Further Changes to !reset would be required, else we would get "Example Title - Permalink - Other Permalink"
Potentially could use str.split("-") on the title and removing the last element?

Updated Racetime.gg Information

---

randobot/handler.py

This PR adds the ability to set the planning time for spoiler log races. The command is `!setplanningtime`. By default, the planning time is 50 minutes. The bot enforces that the minimum planning time is 20 minutes to distribute permalinks properly. Resetting the bot also resets the planning time to 50 minutes. A warning message will appear every ten-minute mark until the race begins.

Add command to set planning time for spoiler log races

---

randobot/constants.py
randobot/handler.py

This PR adds the ability to roll seeds using presets for commonly-used settings rather than specifying the permalink. If the user supplies a permalink, the bot will still use it.
The `!rollseed` command has the following presets:
- `tourney`
- `beginner`
- `co-op`
- `allsanity`
Additionally, `s4` is an alias for `tourney` and `coop` is an alias for `co-op`.
The `!startspoilerlograce` command has the following presets:
- `tourney`
- `allsanity`
Additionally, `s1` is an alias for `tourney`.
Finally, the PR adds the `!presets` command, which lists the presets (but not their aliases) in the chat room.

Presets when rolling seeds

---

randobot/handler.py

Would be nice if we could place the seed hash next to the perma as chat will push the initial message away.
Haven't had time to test this yet.

Put seed hash in raceinfo

---

.flake8
.github/workflows/ci.yml
.gitmodules
Dockerfile
randobot/constants.py
randobot/generator.py
randobot/handler.py

This PR adds the `!rolldevseed` command which rolls a seed using the 1.9.10_dev version of the dev build.
The usage of the `!rolldevseed` command is the same as with the `!rollseed` command, with the main difference being which build of the randomizer to bot uses. I also added a little message after the seed has been rolled to remind runners that they need to be using the 1.9.10_dev build.
For default settings, I just used the current default settings of the build. I considered adding the options currently up for voting for the S5 tournament. However, with random starting item and hint distributions, there'd be too many options to include, in my opinion. Plus, this testing period will not be for much longer anyway.

Add command to roll seeds on dev build

---

.flake8
.gitmodules
randobot/constants.py
randobot/generator.py
randobot/handler.py

This PR adds the command `!randomsettings`, which rolls a seed with random settings specified by the random settings build.
Since the concept of a permalink doesn't make sense with random settings (only the seed name is shared for races), this PR also introduces a new enum `SeedType` to execute the correct behavior when the race room is updated. In the case of random settings, the `permalink` remain set to the default `None`, and the seed name is output in its place.
Finally, we use the `-noui` flag to ensure that the bot runs the randomizer without UI. For the no-ui branches currently employed, the flag has no effect. However, the random settings branch used by the bot to roll seeds has modified behavior so that the `-noui` functions correctly. In the future, no-ui branches should be …

Add `!randomsettings`

---

randobot/constants.py

The old tracker link pointed to a Heroku app which has usage limits. The new tracker is hosted on GitHub Pages instead.

Update RS tracker link

---

randobot/handler.py

This PR update the message the `!breaks` command displays when used during a race.
If breaks have not been set, then it will print that breaks have not been set.
If breaks have been set and there is currently a break, it will print the time until the break ends. Otherwise, it will print the time until the next break. The time will be formatted as per `_get_formatted_duration_str()` to make it more human-readable.

Update `!breaks` when used during a race

---

randobot/handler.py

This PR updates the bot to post a link to a Gist with the spoiler log for a random settings race after the race is finished.
The spoiler log of a random settings seed is only generated if it's run from source, meaning while others can generate spoiler logs if running from source, their seeds won't be the same as the race seed without the correct seed key.

Unlock RSL spoiler log after race

---

randobot/handler.py

Two bugfixes:
- `!spoilerlogurl` worked when a race monitor used it during a RSL race. Adding a separate state variable for the RSL spoiler log should fix this.
- `!breaks` command didn't work when used during a race. This is probably because I forgot the `self` parameter in the method signature.

Fix commands

---

randobot/handler.py

This PR adds a secondary check to determine whether a race is finished for random settings races. Previously, we only check if the race status was `"finished"`. Now, we also count the number of runners that are finished and check if this equals the total number of entrants. If either of these conditions are true, we consider the race to have finished.
This change was made in response to this race https://racetime.gg/twwr/dizzy-morth-2889 in which the spoiler log failed to be shared after the race finished.

Add secondary check for race finish

---

randobot/constants.py

This PR updates the random settings version to v1.3.1, which mainly addresses an issue with seed hashes not matching up.

Update RS version to v1.3.1

---

randobot/constants.py

Fixes the S5 preset's hint distribution: 7 path/7 barren/4 location -> 4 path/4 barren/7 location

Fix S5 preset

---

randobot/constants.py

This PR updates the `beginner` preset to be called `miniblins` and updates the permalink to match the settings used in the Miniblins tournament (old beginner preset + Great Fairies).

Miniblins Preset

---

.flake8
.gitmodules
randobot/constants.py
randobot/generator.py
randobot/handler.py
randobot/tests/test_handler.py
setup-wwrando.sh

`!rollmpseed` rolls a standard mixed pools seed (perma: `MS4xMC4wX2Q1MTRhMjIAQQDfsGDs8CcC4vgJxj0AACQfAAAAEA==`)
`!startmpspoilerlograce` starts a spoiler log race with mixed pools settings

Add commands for mixed pools

---

.github/workflows/ci.yml
.gitmodules
randobot/constants.py
randobot/generator.py
randobot/handler.py
randobot/tests/test_handler.py

This adds support for an updated build of random settings, replacing the existing 1.9-based random settings build. This has a different interface and looks much more like a standard rando with a permalink too, so there are a few changes to go along with bumping the link and version
I plan to put in randobot support directly into the official release when it gets there, so it requires a slightly different set of command-line options from either 1.10 or mixed pools. There's a preparatory commit to handle that
This points the git submodule into my repo for now but we can integrate it into your wwrando repo if you prefer and point to that

random settings v1.4.0-dev3 build update

---

.gitmodules
Dockerfile
setup-wwrando.sh

The idea is to use Docker [multi-stage builds](https://docs.docker.com/build/building/multi-stage/) to bring python from multiple images into a single image
The base image (the first `FROM` at the top of the Dockerfile) will bring in the `/usr/local/bin/python3` symlink, so for things running outside a venv like the rando bot itself, that will be the version used
The other versions only have a `/usr/local/bin/python<version>` executable and need to be called with a full version name. Here that's only 3.10 but we could include any other version for which there is an official docker image with the same construct in the future. The process is somewhat manual/copy-pasty but shouldn't be too difficult to maintain, since python installations are fairly self-contained with a binary, a shared …

Support multiple versions of python in parallel

---

randobot/constants.py
randobot/tests/test_handler.py

This PR updates the permalinks for the Miniblins presets for the 2025 season.
The settings can be found in the [tournament document](<https://docs.google.com/document/d/19vT68eU6PepD2BD2ZjR9ikElfqs8pXfqQucZ-TcscV8/edit?usp=sharing>).

Update Miniblins Permalinks

---

randobot/constants.py
randobot/tests/test_handler.py

This PR fixes the permalinks that use the S8 build. I used the version of the randomizer that doesn't include the git commit tag to generate the old ones. The new ones were generated using the release build.

Fix S8 permalinks
